# Use root/example as user/password credentials
version: '3.1'

services:

  mydb:
    image: mysql:8
    container_name: mysqlc
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: 1234
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ../appdata/dbdata:/var/lib/mysql