version: '3.1'
services:

  myapi:
    image: laravel:1.0
    container_name: laravel
    ports:
      - 8000:8000
    depends_on: 
      - mydb
    volumes: 
      - .:/app
    working_dir: /root/api
    command: "php artisan serve --host=0.0.0.0 --port=8000"

  mydb:
    image: mysql:8
    container_name: mysqlc
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: 1234
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./dbdata:/var/lib/mysql

  mydbadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mydbadminc
    ports:
      - 8088:80
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      PMA_HOST: mydb
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    depends_on:
      - mydb